services:
  db:
    image: postgres
    # restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    entrypoint: sh
    command: -c 'mkdir -p /data && /usr/bin/minio server --console-address ":9090" /data'
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
      MINIO_REGION: us-east-1
      MINIO_DOMAIN: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - ./tmp/minio/:/data

  api:
    build:
      context: ./code/csharp/Nebu
      dockerfile: Dockerfile.api
    environment:
      - DOTNET_ENVIRONMENT=Docker
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
