services:
  db:
    image: postgres
    # restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./code/csharp/Nebu
      dockerfile: Dockerfile.api
    environment:
      - DOTNET_ENVIRONMENT=Docker
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
