/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Nebu.Api
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  BucketReadModel,
  BucketWriteModel
} from '.././model'



export const getApiBuckets = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<BucketReadModel[]>> => {
    
    return axios.default.get(
      `/api/Buckets`,options
    );
  }


export const getGetApiBucketsQueryKey = () => {
    return [`/api/Buckets`] as const;
    }

    
export const getGetApiBucketsQueryOptions = <TData = Awaited<ReturnType<typeof getApiBuckets>>, TError = AxiosError<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiBuckets>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiBucketsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiBuckets>>> = ({ signal }) => getApiBuckets({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiBuckets>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiBucketsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiBuckets>>>
export type GetApiBucketsQueryError = AxiosError<unknown>

export const useGetApiBuckets = <TData = Awaited<ReturnType<typeof getApiBuckets>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiBuckets>>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetApiBucketsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const postApiBuckets = (
    bucketWriteModel: BucketWriteModel, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<BucketReadModel>> => {
    
    return axios.default.post(
      `/api/Buckets`,
      bucketWriteModel,options
    );
  }



export const getPostApiBucketsMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiBuckets>>, TError,{data: BucketWriteModel}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiBuckets>>, TError,{data: BucketWriteModel}, TContext> => {
 const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiBuckets>>, {data: BucketWriteModel}> = (props) => {
          const {data} = props ?? {};

          return  postApiBuckets(data,axiosOptions)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type PostApiBucketsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiBuckets>>>
    export type PostApiBucketsMutationBody = BucketWriteModel
    export type PostApiBucketsMutationError = AxiosError<unknown>

    export const usePostApiBuckets = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiBuckets>>, TError,{data: BucketWriteModel}, TContext>, axios?: AxiosRequestConfig}
) => {

      const mutationOptions = getPostApiBucketsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    