/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Nebu.Api
 * OpenAPI spec version: 1.0
 */

export interface BucketReadModel {
  id?: string;
  uri?: string | null;
  userId?: string;
}
