/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * Nebu.Api
 * OpenAPI spec version: 1.0
 */

export interface UserReadModel {
  apiKey?: string | null;
  id?: string;
  name?: string | null;
}
